### ISSUE TITLE
Rename default fieldtype identier to avoid conflicts with old, ezcommunity version

### ISSUE THREAD

**Issue by gggeek** [ezsystems/ezplatform-matrix-fieldtype#16]
As far as I can see, it makes no sense to call this fieldtype 'ezmatrix', since it is not compatible with the previous 'ezmatrix'.
What about ezmatrix2 or ezplatformmatrix?

**Comment by emodric** [comment]
I wholeheartedly agree. It does not benefit anyone to have the same identifier as the community version of ezmatrix field type. It only causes unnecessary problems.

**Comment by andrerom** [comment]
Closing as wont fix, and closing down issues here. Please use JIRA.
